server:
  port: 8081

spring:
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
      password: password
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

regCenter:
  serverList: localhost:2181
  namespace: elastic-job-lite-springboot

simpleJob:
  cron: 0/20 * * * * ?
  shardingTotalCount: 2
  listener: com.yliu.elasticjob.Listener.MyListener

dataflowJob:
  cron: 0/5 * * * * ?
  shardingTotalCount: 2
  listener: com.yliu.elasticjob.Listener.MyListener
  shardingItemParameters: 0=Eveb,1=Odd


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yfliu.Model

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml