server:
  port: 8081

spring:
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
#      url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
#      username: root
#      password: password
      one:  #数据源1
        jdbc-url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
        username: root
        password: password
        driver-class-name: com.mysql.jdbc.Driver
      two: #数据源2
        jdbc-url: jdbc:mysql://127.0.0.1:3306/mytest1?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
        username: root
        password: password
        driver-class-name: com.mysql.jdbc.Driver
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
    initialization-mode: always
    schema: classpath:sql/init.sql

regCenter:
  serverList: localhost:2181
  namespace: elastic-job-lite-springboot

dataflowJob:
  cron: 0/5 * * * * ?
  shardingTotalCount: 1
#  listener: com.yliu.elasticjob.Listener.MyListener
  shardingItemParameters: 0=One


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yfliu.Model

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml