server:
  port: 8081

# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mytest?characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false&requireSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password

# zk配置
regCenter:
  serverList: localhost:2181
  namespace: elastic-job-lite-springboot

# 定时任务配置
simpleJob:
  cron: 0 0/1 * * * ?
  shardingTotalCount: 3


