server:
  port: 8081

spring:
  datasource:
    name: mysql_test
    one:  #数据源1
      jdbc-url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
      password: password
      driver-class-name: com.mysql.jdbc.Driver
    two: #数据源2
      jdbc-url: jdbc:mysql://127.0.0.1:3306/mytest1?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
      password: password
      driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    schema: classpath:sql/init.sql

regCenter:
  serverList: localhost:2181
  namespace: elastic-job-lite-springboot

dataflowJob:
  cron: 0/10 * * * * ?
  shardingTotalCount: 1
#  listener: com.yliu.elasticjob.Listener.MyListener
  shardingItemParameters: 0=One


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yfliu.Model

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml